-- MySQL Script generated by MySQL Workbench
-- Wed May 17 22:15:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `user_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`data_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`data_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `dni` VARCHAR(255) NOT NULL,
  `gender` VARCHAR(255) NOT NULL,
  `phonenumber` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userID_has_data` INT NOT NULL,
  `dataID_user_has_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_has_data_id_idx` (`userID_has_data` ASC) VISIBLE,
  INDEX `data_user_has_userId_idx` (`dataID_user_has_user` ASC) VISIBLE,
  UNIQUE INDEX `userID_has_data_UNIQUE` (`userID_has_data` ASC) VISIBLE,
  UNIQUE INDEX `dataID_user_has_user_UNIQUE` (`dataID_user_has_user` ASC) VISIBLE,
  CONSTRAINT `user_has_data_id`
    FOREIGN KEY (`userID_has_data`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `data_user_has_userId`
    FOREIGN KEY (`dataID_user_has_user`)
    REFERENCES `mydb`.`data_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userID_has_group` INT NOT NULL,
  `groupID_has_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_has_group_idx` (`userID_has_group` ASC) VISIBLE,
  INDEX `group_has_user_idx` (`groupID_has_user` ASC) VISIBLE,
  CONSTRAINT `user_has_group`
    FOREIGN KEY (`userID_has_group`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `group_has_user`
    FOREIGN KEY (`groupID_has_user`)
    REFERENCES `mydb`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`access` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_of_method` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group_access` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_group_has_access` INT NOT NULL,
  `id_access_has_group` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_group_has_access_idx` (`id_group_has_access` ASC) VISIBLE,
  INDEX `id_access_has_group_idx` (`id_access_has_group` ASC) VISIBLE,
  CONSTRAINT `id_group_has_access`
    FOREIGN KEY (`id_group_has_access`)
    REFERENCES `mydb`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_access_has_group`
    FOREIGN KEY (`id_access_has_group`)
    REFERENCES `mydb`.`access` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`access_has_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`access_has_resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `access_has_resource` INT NOT NULL,
  `resource_has_access` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `access_has_resource_idx` (`access_has_resource` ASC) VISIBLE,
  INDEX `resource_has_access_idx` (`resource_has_access` ASC) VISIBLE,
  CONSTRAINT `access_has_resource`
    FOREIGN KEY (`access_has_resource`)
    REFERENCES `mydb`.`access` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `resource_has_access`
    FOREIGN KEY (`resource_has_access`)
    REFERENCES `mydb`.`resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
