-- MySQL Script generated by MySQL Workbench
-- Thu May 11 15:57:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `idgroup` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idgroup`, `name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`data_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`data_user` (
  `iddata_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `dni` VARCHAR(255) NOT NULL,
  `gender` VARCHAR(255) NOT NULL,
  `phonenumber` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iddata_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_data` (
  `iduser_has_data` INT NOT NULL AUTO_INCREMENT,
  `userID_has_data` INT NOT NULL,
  `dataID_user_has_user` INT NOT NULL,
  PRIMARY KEY (`iduser_has_data`),
  INDEX `user_has_data_id_idx` (`userID_has_data` ASC) VISIBLE,
  INDEX `data_user_has_userId_idx` (`dataID_user_has_user` ASC) VISIBLE,
  CONSTRAINT `user_has_data_id`
    FOREIGN KEY (`userID_has_data`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `data_user_has_userId`
    FOREIGN KEY (`dataID_user_has_user`)
    REFERENCES `mydb`.`data_user` (`iddata_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_group` (
  `iduser_has_group` INT NOT NULL AUTO_INCREMENT,
  `userID_has_group` INT NOT NULL,
  `groupID_has_user` INT NOT NULL,
  PRIMARY KEY (`iduser_has_group`),
  INDEX `user_has_group_idx` (`userID_has_group` ASC) VISIBLE,
  INDEX `group_has_user_idx` (`groupID_has_user` ASC) VISIBLE,
  CONSTRAINT `user_has_group`
    FOREIGN KEY (`userID_has_group`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `group_has_user`
    FOREIGN KEY (`groupID_has_user`)
    REFERENCES `mydb`.`group` (`idgroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
